import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Footer from "@/components/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import NavbarMobile from "@/components/Navbar/NavbarMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` min-h-screen flex flex-col bg-white `}>
        <header className="fixed top-6 left-0 w-full z-50 hidden md:block">
          <Navbar />
        </header>
        <header className="fixed top-8 left-8 w-full z-50 md:hidden sm:block">
          <NavbarMobile />
        </header>
        <AppRouterCacheProvider options={{ key: "mui", prepend: true }}>
          <main className="flex-1 mb-12">{children}</main>
        </AppRouterCacheProvider>
        <Footer />
      </body>
    </html>
  );
}
